//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Character/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerActionControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerActionControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""General"",
            ""id"": ""3e1f8e61-f499-4604-8d64-56f1c7156db6"",
            ""actions"": [
                {
                    ""name"": ""MoveHorizontal"",
                    ""type"": ""PassThrough"",
                    ""id"": ""82a78adc-0946-45b0-87db-7547be79f78f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveVertical"",
                    ""type"": ""Value"",
                    ""id"": ""5a0e7a14-6442-4449-9efa-2b5f6bf057f6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OpenSpellBook"",
                    ""type"": ""Button"",
                    ""id"": ""b7956a4c-1d27-45e8-8875-1d90a56fa41d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""fdac0a8e-649b-45d2-82fd-a0357870a5de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drop"",
                    ""type"": ""Button"",
                    ""id"": ""4a26f88d-088d-45b2-8271-35410782406f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot0"",
                    ""type"": ""Button"",
                    ""id"": ""ec7f9830-a854-4136-8235-281b7dce03f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot1"",
                    ""type"": ""Button"",
                    ""id"": ""8729c05b-3a5d-45f1-831e-f8c171fb7ff8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot2"",
                    ""type"": ""Button"",
                    ""id"": ""8a0056a7-69c8-4c18-966f-9148f12c7468"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot3"",
                    ""type"": ""Button"",
                    ""id"": ""a51b0b8d-4d9f-4eba-b42b-99b2a17ff516"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot4"",
                    ""type"": ""Button"",
                    ""id"": ""2a460482-869a-4296-85eb-6b4f6f3792e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot5"",
                    ""type"": ""Button"",
                    ""id"": ""bdacd7a5-0d84-4533-a46f-de2dcaac6157"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot6"",
                    ""type"": ""Button"",
                    ""id"": ""5e73b555-7d13-416f-b942-7fa3be75d9fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slot7"",
                    ""type"": ""Button"",
                    ""id"": ""e5201627-a9de-45e9-b172-0554a8f38666"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeSlots"",
                    ""type"": ""Value"",
                    ""id"": ""adf90bf2-4ae2-4711-8e28-709b2caf290f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FreeReputation"",
                    ""type"": ""Button"",
                    ""id"": ""57e64946-f744-4450-a649-4a1d0f6b93d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FreeExp"",
                    ""type"": ""Button"",
                    ""id"": ""672c5633-d22a-403f-920d-744a8161ac3a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""HorizontalArrows"",
                    ""id"": ""06eeabe0-b760-4b0c-b5dd-f6a01d1b5b07"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveHorizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""191bd8fc-9a5c-466a-82a3-c99298bdf473"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""43e9ed83-b9b4-4eb6-ab45-369427f9969b"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""HorizontalLetters"",
                    ""id"": ""d16cda33-41ff-471c-acbd-d406343fad3a"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveHorizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""894a7088-1573-4f9d-bedf-78186454a3b4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""f5b0572b-0209-4ec9-906e-d4677d6dec82"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""76a38ee4-ca1c-4113-ae31-ac2516c23e52"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe91e10b-20f9-448b-b0a3-bcbe0691b81f"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenSpellBook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82011270-4a93-4687-852e-1d646c5e1f80"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a5ad0e4-d977-46c7-938d-bf68e872f22d"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2bcdb4c5-5d0c-44fb-8daa-e9e441f81ef8"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07fda538-c7ff-4f13-8411-a6e131b903cb"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8532d3f-74f9-4b09-a424-82473aa01fe0"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cc239c2-e11e-4b7e-8bae-1253084bc36e"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05aff15d-fae5-4ecb-9993-9bbb7a9be16f"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""def25abc-1060-46e8-ba93-db5ed6a0ac88"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slot6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""VerticalArrows"",
                    ""id"": ""178e54a1-f28c-4bd7-ab3f-a0267edb37a7"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveVertical"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""df58faa1-ab92-44ca-b5e0-e895f81df327"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""c82650a3-48f0-4395-8671-b70e1f712ca2"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""VerticalLetters"",
                    ""id"": ""be48ad07-c0e4-4f01-9c24-609fb24c1774"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveVertical"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""b22abdea-97d0-446d-848a-6b70d4ab9b61"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ee2102dd-d21c-4c1d-8546-c19c4ba4c5f8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b2895c25-efac-4101-8c3b-b15d2f7b290a"",
                    ""path"": ""<Keyboard>/numpadMinus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FreeExp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9fad119b-ab41-4f46-940e-baae6caa59d4"",
                    ""path"": ""<Keyboard>/numpadPlus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FreeReputation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca61d095-760e-40b8-96dd-2e6c3d6819e7"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeSlots"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4dab66b-6555-4c3d-be7b-3a553d7468c6"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""SpellBook"",
            ""id"": ""b3fa0148-9461-4bca-ac5f-3a31d01a6b7c"",
            ""actions"": [
                {
                    ""name"": ""CloseSpellBook"",
                    ""type"": ""Button"",
                    ""id"": ""74c025a5-6558-484c-b736-8e817930e483"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PageLeft"",
                    ""type"": ""Button"",
                    ""id"": ""e4da9af4-a1f1-4e63-b405-2d3c07ee003d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PageRight"",
                    ""type"": ""Button"",
                    ""id"": ""afce8bac-218e-476f-84ae-c9b4c5e9271b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigateLeft"",
                    ""type"": ""Button"",
                    ""id"": ""f5e3b74c-5143-4691-bfee-60ad3f6fe4ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigateRight"",
                    ""type"": ""Button"",
                    ""id"": ""74b5d347-fe26-46e1-9959-c1e7b793a6f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigateUp"",
                    ""type"": ""Button"",
                    ""id"": ""0c3d02ef-ffd5-4e42-8d6b-5975ce16d58c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigateDown"",
                    ""type"": ""Button"",
                    ""id"": ""7aaecaaa-a40d-4fad-a340-aa80fe0d3ad0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""2b939ceb-4444-4272-9f2f-ab2ba2ee474c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drop"",
                    ""type"": ""Button"",
                    ""id"": ""42840cc0-bcf3-4af7-8abf-d97fbfb9b74c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FreeExp"",
                    ""type"": ""Button"",
                    ""id"": ""eded31f5-c5a8-4a2f-a663-bfe31976e289"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FreeReputation"",
                    ""type"": ""Button"",
                    ""id"": ""90d642ef-b078-497e-a9d7-d5e3b6748bc4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a2bc7025-404b-4a6e-aa72-02937673ac1c"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PageLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6bccaf8-fc23-4508-8ff1-23779fb2ca53"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PageRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""274e0073-8726-4d48-a8dd-770b166309a5"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b62d7daf-898b-41a2-8b39-e94f91d002d0"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b92c39d-6614-4bd7-82c1-d67cca996817"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62532ee5-c86e-4fa1-a8f5-c698a0484edb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c812b249-2685-46db-8f5b-1428910232c6"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4636284-18b7-4579-a613-bd979581cac9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84d224af-1638-4b63-b841-a57d15ff5e32"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2b917c3-0d8e-4757-82ca-562a3683c204"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c6ec982-30a3-417e-a871-d0a808f3f0c2"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseSpellBook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""529d2e5c-ffe1-4c56-a4d7-c8060a0fe7ed"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseSpellBook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a323ce7-672a-43af-9c05-3fe145cdd016"",
                    ""path"": ""<Keyboard>/numpadPlus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FreeReputation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77cbfd0c-24ea-47b8-b728-9bfcf271a66c"",
                    ""path"": ""<Keyboard>/numpadMinus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FreeExp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77ca5fd0-3098-455f-9ee5-36a4e8ae74d0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4f07b0e-4172-44eb-9892-3ab564207e8d"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e5014b9-3568-4a54-bb54-72e4269c0a1c"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // General
        m_General = asset.FindActionMap("General", throwIfNotFound: true);
        m_General_MoveHorizontal = m_General.FindAction("MoveHorizontal", throwIfNotFound: true);
        m_General_MoveVertical = m_General.FindAction("MoveVertical", throwIfNotFound: true);
        m_General_OpenSpellBook = m_General.FindAction("OpenSpellBook", throwIfNotFound: true);
        m_General_Interact = m_General.FindAction("Interact", throwIfNotFound: true);
        m_General_Drop = m_General.FindAction("Drop", throwIfNotFound: true);
        m_General_Slot0 = m_General.FindAction("Slot0", throwIfNotFound: true);
        m_General_Slot1 = m_General.FindAction("Slot1", throwIfNotFound: true);
        m_General_Slot2 = m_General.FindAction("Slot2", throwIfNotFound: true);
        m_General_Slot3 = m_General.FindAction("Slot3", throwIfNotFound: true);
        m_General_Slot4 = m_General.FindAction("Slot4", throwIfNotFound: true);
        m_General_Slot5 = m_General.FindAction("Slot5", throwIfNotFound: true);
        m_General_Slot6 = m_General.FindAction("Slot6", throwIfNotFound: true);
        m_General_Slot7 = m_General.FindAction("Slot7", throwIfNotFound: true);
        m_General_ChangeSlots = m_General.FindAction("ChangeSlots", throwIfNotFound: true);
        m_General_FreeReputation = m_General.FindAction("FreeReputation", throwIfNotFound: true);
        m_General_FreeExp = m_General.FindAction("FreeExp", throwIfNotFound: true);
        // SpellBook
        m_SpellBook = asset.FindActionMap("SpellBook", throwIfNotFound: true);
        m_SpellBook_CloseSpellBook = m_SpellBook.FindAction("CloseSpellBook", throwIfNotFound: true);
        m_SpellBook_PageLeft = m_SpellBook.FindAction("PageLeft", throwIfNotFound: true);
        m_SpellBook_PageRight = m_SpellBook.FindAction("PageRight", throwIfNotFound: true);
        m_SpellBook_NavigateLeft = m_SpellBook.FindAction("NavigateLeft", throwIfNotFound: true);
        m_SpellBook_NavigateRight = m_SpellBook.FindAction("NavigateRight", throwIfNotFound: true);
        m_SpellBook_NavigateUp = m_SpellBook.FindAction("NavigateUp", throwIfNotFound: true);
        m_SpellBook_NavigateDown = m_SpellBook.FindAction("NavigateDown", throwIfNotFound: true);
        m_SpellBook_Select = m_SpellBook.FindAction("Select", throwIfNotFound: true);
        m_SpellBook_Drop = m_SpellBook.FindAction("Drop", throwIfNotFound: true);
        m_SpellBook_FreeExp = m_SpellBook.FindAction("FreeExp", throwIfNotFound: true);
        m_SpellBook_FreeReputation = m_SpellBook.FindAction("FreeReputation", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // General
    private readonly InputActionMap m_General;
    private IGeneralActions m_GeneralActionsCallbackInterface;
    private readonly InputAction m_General_MoveHorizontal;
    private readonly InputAction m_General_MoveVertical;
    private readonly InputAction m_General_OpenSpellBook;
    private readonly InputAction m_General_Interact;
    private readonly InputAction m_General_Drop;
    private readonly InputAction m_General_Slot0;
    private readonly InputAction m_General_Slot1;
    private readonly InputAction m_General_Slot2;
    private readonly InputAction m_General_Slot3;
    private readonly InputAction m_General_Slot4;
    private readonly InputAction m_General_Slot5;
    private readonly InputAction m_General_Slot6;
    private readonly InputAction m_General_Slot7;
    private readonly InputAction m_General_ChangeSlots;
    private readonly InputAction m_General_FreeReputation;
    private readonly InputAction m_General_FreeExp;
    public struct GeneralActions
    {
        private @PlayerActionControls m_Wrapper;
        public GeneralActions(@PlayerActionControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveHorizontal => m_Wrapper.m_General_MoveHorizontal;
        public InputAction @MoveVertical => m_Wrapper.m_General_MoveVertical;
        public InputAction @OpenSpellBook => m_Wrapper.m_General_OpenSpellBook;
        public InputAction @Interact => m_Wrapper.m_General_Interact;
        public InputAction @Drop => m_Wrapper.m_General_Drop;
        public InputAction @Slot0 => m_Wrapper.m_General_Slot0;
        public InputAction @Slot1 => m_Wrapper.m_General_Slot1;
        public InputAction @Slot2 => m_Wrapper.m_General_Slot2;
        public InputAction @Slot3 => m_Wrapper.m_General_Slot3;
        public InputAction @Slot4 => m_Wrapper.m_General_Slot4;
        public InputAction @Slot5 => m_Wrapper.m_General_Slot5;
        public InputAction @Slot6 => m_Wrapper.m_General_Slot6;
        public InputAction @Slot7 => m_Wrapper.m_General_Slot7;
        public InputAction @ChangeSlots => m_Wrapper.m_General_ChangeSlots;
        public InputAction @FreeReputation => m_Wrapper.m_General_FreeReputation;
        public InputAction @FreeExp => m_Wrapper.m_General_FreeExp;
        public InputActionMap Get() { return m_Wrapper.m_General; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GeneralActions set) { return set.Get(); }
        public void SetCallbacks(IGeneralActions instance)
        {
            if (m_Wrapper.m_GeneralActionsCallbackInterface != null)
            {
                @MoveHorizontal.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMoveHorizontal;
                @MoveHorizontal.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMoveHorizontal;
                @MoveHorizontal.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMoveHorizontal;
                @MoveVertical.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMoveVertical;
                @MoveVertical.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMoveVertical;
                @MoveVertical.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnMoveVertical;
                @OpenSpellBook.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnOpenSpellBook;
                @OpenSpellBook.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnOpenSpellBook;
                @OpenSpellBook.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnOpenSpellBook;
                @Interact.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnInteract;
                @Drop.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnDrop;
                @Drop.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnDrop;
                @Drop.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnDrop;
                @Slot0.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot0;
                @Slot0.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot0;
                @Slot0.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot0;
                @Slot1.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot1;
                @Slot1.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot1;
                @Slot1.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot1;
                @Slot2.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot2;
                @Slot2.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot2;
                @Slot2.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot2;
                @Slot3.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot3;
                @Slot3.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot3;
                @Slot3.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot3;
                @Slot4.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot4;
                @Slot4.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot4;
                @Slot4.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot4;
                @Slot5.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot5;
                @Slot5.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot5;
                @Slot5.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot5;
                @Slot6.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot6;
                @Slot6.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot6;
                @Slot6.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot6;
                @Slot7.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot7;
                @Slot7.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot7;
                @Slot7.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnSlot7;
                @ChangeSlots.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnChangeSlots;
                @ChangeSlots.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnChangeSlots;
                @ChangeSlots.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnChangeSlots;
                @FreeReputation.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnFreeReputation;
                @FreeReputation.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnFreeReputation;
                @FreeReputation.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnFreeReputation;
                @FreeExp.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnFreeExp;
                @FreeExp.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnFreeExp;
                @FreeExp.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnFreeExp;
            }
            m_Wrapper.m_GeneralActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MoveHorizontal.started += instance.OnMoveHorizontal;
                @MoveHorizontal.performed += instance.OnMoveHorizontal;
                @MoveHorizontal.canceled += instance.OnMoveHorizontal;
                @MoveVertical.started += instance.OnMoveVertical;
                @MoveVertical.performed += instance.OnMoveVertical;
                @MoveVertical.canceled += instance.OnMoveVertical;
                @OpenSpellBook.started += instance.OnOpenSpellBook;
                @OpenSpellBook.performed += instance.OnOpenSpellBook;
                @OpenSpellBook.canceled += instance.OnOpenSpellBook;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @Drop.started += instance.OnDrop;
                @Drop.performed += instance.OnDrop;
                @Drop.canceled += instance.OnDrop;
                @Slot0.started += instance.OnSlot0;
                @Slot0.performed += instance.OnSlot0;
                @Slot0.canceled += instance.OnSlot0;
                @Slot1.started += instance.OnSlot1;
                @Slot1.performed += instance.OnSlot1;
                @Slot1.canceled += instance.OnSlot1;
                @Slot2.started += instance.OnSlot2;
                @Slot2.performed += instance.OnSlot2;
                @Slot2.canceled += instance.OnSlot2;
                @Slot3.started += instance.OnSlot3;
                @Slot3.performed += instance.OnSlot3;
                @Slot3.canceled += instance.OnSlot3;
                @Slot4.started += instance.OnSlot4;
                @Slot4.performed += instance.OnSlot4;
                @Slot4.canceled += instance.OnSlot4;
                @Slot5.started += instance.OnSlot5;
                @Slot5.performed += instance.OnSlot5;
                @Slot5.canceled += instance.OnSlot5;
                @Slot6.started += instance.OnSlot6;
                @Slot6.performed += instance.OnSlot6;
                @Slot6.canceled += instance.OnSlot6;
                @Slot7.started += instance.OnSlot7;
                @Slot7.performed += instance.OnSlot7;
                @Slot7.canceled += instance.OnSlot7;
                @ChangeSlots.started += instance.OnChangeSlots;
                @ChangeSlots.performed += instance.OnChangeSlots;
                @ChangeSlots.canceled += instance.OnChangeSlots;
                @FreeReputation.started += instance.OnFreeReputation;
                @FreeReputation.performed += instance.OnFreeReputation;
                @FreeReputation.canceled += instance.OnFreeReputation;
                @FreeExp.started += instance.OnFreeExp;
                @FreeExp.performed += instance.OnFreeExp;
                @FreeExp.canceled += instance.OnFreeExp;
            }
        }
    }
    public GeneralActions @General => new GeneralActions(this);

    // SpellBook
    private readonly InputActionMap m_SpellBook;
    private ISpellBookActions m_SpellBookActionsCallbackInterface;
    private readonly InputAction m_SpellBook_CloseSpellBook;
    private readonly InputAction m_SpellBook_PageLeft;
    private readonly InputAction m_SpellBook_PageRight;
    private readonly InputAction m_SpellBook_NavigateLeft;
    private readonly InputAction m_SpellBook_NavigateRight;
    private readonly InputAction m_SpellBook_NavigateUp;
    private readonly InputAction m_SpellBook_NavigateDown;
    private readonly InputAction m_SpellBook_Select;
    private readonly InputAction m_SpellBook_Drop;
    private readonly InputAction m_SpellBook_FreeExp;
    private readonly InputAction m_SpellBook_FreeReputation;
    public struct SpellBookActions
    {
        private @PlayerActionControls m_Wrapper;
        public SpellBookActions(@PlayerActionControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @CloseSpellBook => m_Wrapper.m_SpellBook_CloseSpellBook;
        public InputAction @PageLeft => m_Wrapper.m_SpellBook_PageLeft;
        public InputAction @PageRight => m_Wrapper.m_SpellBook_PageRight;
        public InputAction @NavigateLeft => m_Wrapper.m_SpellBook_NavigateLeft;
        public InputAction @NavigateRight => m_Wrapper.m_SpellBook_NavigateRight;
        public InputAction @NavigateUp => m_Wrapper.m_SpellBook_NavigateUp;
        public InputAction @NavigateDown => m_Wrapper.m_SpellBook_NavigateDown;
        public InputAction @Select => m_Wrapper.m_SpellBook_Select;
        public InputAction @Drop => m_Wrapper.m_SpellBook_Drop;
        public InputAction @FreeExp => m_Wrapper.m_SpellBook_FreeExp;
        public InputAction @FreeReputation => m_Wrapper.m_SpellBook_FreeReputation;
        public InputActionMap Get() { return m_Wrapper.m_SpellBook; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SpellBookActions set) { return set.Get(); }
        public void SetCallbacks(ISpellBookActions instance)
        {
            if (m_Wrapper.m_SpellBookActionsCallbackInterface != null)
            {
                @CloseSpellBook.started -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnCloseSpellBook;
                @CloseSpellBook.performed -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnCloseSpellBook;
                @CloseSpellBook.canceled -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnCloseSpellBook;
                @PageLeft.started -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnPageLeft;
                @PageLeft.performed -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnPageLeft;
                @PageLeft.canceled -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnPageLeft;
                @PageRight.started -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnPageRight;
                @PageRight.performed -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnPageRight;
                @PageRight.canceled -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnPageRight;
                @NavigateLeft.started -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnNavigateLeft;
                @NavigateLeft.performed -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnNavigateLeft;
                @NavigateLeft.canceled -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnNavigateLeft;
                @NavigateRight.started -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnNavigateRight;
                @NavigateRight.performed -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnNavigateRight;
                @NavigateRight.canceled -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnNavigateRight;
                @NavigateUp.started -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnNavigateUp;
                @NavigateUp.performed -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnNavigateUp;
                @NavigateUp.canceled -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnNavigateUp;
                @NavigateDown.started -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnNavigateDown;
                @NavigateDown.performed -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnNavigateDown;
                @NavigateDown.canceled -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnNavigateDown;
                @Select.started -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnSelect;
                @Drop.started -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnDrop;
                @Drop.performed -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnDrop;
                @Drop.canceled -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnDrop;
                @FreeExp.started -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnFreeExp;
                @FreeExp.performed -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnFreeExp;
                @FreeExp.canceled -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnFreeExp;
                @FreeReputation.started -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnFreeReputation;
                @FreeReputation.performed -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnFreeReputation;
                @FreeReputation.canceled -= m_Wrapper.m_SpellBookActionsCallbackInterface.OnFreeReputation;
            }
            m_Wrapper.m_SpellBookActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CloseSpellBook.started += instance.OnCloseSpellBook;
                @CloseSpellBook.performed += instance.OnCloseSpellBook;
                @CloseSpellBook.canceled += instance.OnCloseSpellBook;
                @PageLeft.started += instance.OnPageLeft;
                @PageLeft.performed += instance.OnPageLeft;
                @PageLeft.canceled += instance.OnPageLeft;
                @PageRight.started += instance.OnPageRight;
                @PageRight.performed += instance.OnPageRight;
                @PageRight.canceled += instance.OnPageRight;
                @NavigateLeft.started += instance.OnNavigateLeft;
                @NavigateLeft.performed += instance.OnNavigateLeft;
                @NavigateLeft.canceled += instance.OnNavigateLeft;
                @NavigateRight.started += instance.OnNavigateRight;
                @NavigateRight.performed += instance.OnNavigateRight;
                @NavigateRight.canceled += instance.OnNavigateRight;
                @NavigateUp.started += instance.OnNavigateUp;
                @NavigateUp.performed += instance.OnNavigateUp;
                @NavigateUp.canceled += instance.OnNavigateUp;
                @NavigateDown.started += instance.OnNavigateDown;
                @NavigateDown.performed += instance.OnNavigateDown;
                @NavigateDown.canceled += instance.OnNavigateDown;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @Drop.started += instance.OnDrop;
                @Drop.performed += instance.OnDrop;
                @Drop.canceled += instance.OnDrop;
                @FreeExp.started += instance.OnFreeExp;
                @FreeExp.performed += instance.OnFreeExp;
                @FreeExp.canceled += instance.OnFreeExp;
                @FreeReputation.started += instance.OnFreeReputation;
                @FreeReputation.performed += instance.OnFreeReputation;
                @FreeReputation.canceled += instance.OnFreeReputation;
            }
        }
    }
    public SpellBookActions @SpellBook => new SpellBookActions(this);
    public interface IGeneralActions
    {
        void OnMoveHorizontal(InputAction.CallbackContext context);
        void OnMoveVertical(InputAction.CallbackContext context);
        void OnOpenSpellBook(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnDrop(InputAction.CallbackContext context);
        void OnSlot0(InputAction.CallbackContext context);
        void OnSlot1(InputAction.CallbackContext context);
        void OnSlot2(InputAction.CallbackContext context);
        void OnSlot3(InputAction.CallbackContext context);
        void OnSlot4(InputAction.CallbackContext context);
        void OnSlot5(InputAction.CallbackContext context);
        void OnSlot6(InputAction.CallbackContext context);
        void OnSlot7(InputAction.CallbackContext context);
        void OnChangeSlots(InputAction.CallbackContext context);
        void OnFreeReputation(InputAction.CallbackContext context);
        void OnFreeExp(InputAction.CallbackContext context);
    }
    public interface ISpellBookActions
    {
        void OnCloseSpellBook(InputAction.CallbackContext context);
        void OnPageLeft(InputAction.CallbackContext context);
        void OnPageRight(InputAction.CallbackContext context);
        void OnNavigateLeft(InputAction.CallbackContext context);
        void OnNavigateRight(InputAction.CallbackContext context);
        void OnNavigateUp(InputAction.CallbackContext context);
        void OnNavigateDown(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnDrop(InputAction.CallbackContext context);
        void OnFreeExp(InputAction.CallbackContext context);
        void OnFreeReputation(InputAction.CallbackContext context);
    }
}
